// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CharonBridge>>
abstract class CharonBridge implements RustOpaqueInterface {
  /// Must be called exactly once per `CharonBridge` instance; forwards
  /// every `AppEvent` (from xray, the tunnel, and the log bridge) to the
  /// returned Dart stream for the lifetime of the app. Mirrors the egui
  /// shell's `TunnelStopped` handling: clears the tunnel slot and kicks
  /// off the Windows network-reset safety net before the event reaches Dart.
  Stream<CharonEvent> events();

  factory CharonBridge() =>
      RustLib.instance.api.crateApiSimpleCharonBridgeNew();

  /// `tun_fd` is ignored on Windows (which manages its own wintun adapter)
  /// and required on Android (the fd comes from `VpnService.Builder.establish()`
  /// on the Kotlin side). Kept as one signature, rather than two cfg-gated
  /// methods, so a single frb codegen pass produces one Dart API usable on
  /// both platforms.
  Future<void> startTunnel({
    required String proxyUrl,
    required String serverIp,
    int? tunFd,
  });

  Future<void> startXray({
    required String xrayPath,
    required String configPath,
  });

  Future<void> stopTunnel();

  Future<void> stopXray();
}

@freezed
sealed class CharonEvent with _$CharonEvent {
  const CharonEvent._();

  const factory CharonEvent.xrayLog(String field0) = CharonEvent_XrayLog;
  const factory CharonEvent.tunnelLog(String field0) = CharonEvent_TunnelLog;
  const factory CharonEvent.tunnelStopped({required bool ok, String? message}) =
      CharonEvent_TunnelStopped;
}
