// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CharonBridge>>
abstract class CharonBridge implements RustOpaqueInterface {
  /// Must be called exactly once per `CharonBridge` instance; forwards
  /// every `AppEvent` (xray/tunnel logs, connection lifecycle, kill-switch
  /// and reconnect state) to the returned Dart stream for the lifetime of
  /// the app. The supervisor already handles the Windows network-reset
  /// safety net and reconnect decisions internally, so this is a plain
  /// relay.
  Stream<CharonEvent> events();

  factory CharonBridge() =>
      RustLib.instance.api.crateApiSimpleCharonBridgeNew();

  /// When on, an unexpected xray or tunnel drop is retried automatically
  /// (up to 5 attempts, 5s apart) instead of just reporting the failure.
  Future<void> setAutoReconnect({required bool enabled});

  /// When on, an unexpected xray crash leaves the TUN adapter in place
  /// (new connections fail closed) instead of tearing the tunnel down -
  /// see `charon_core::supervisor::Supervisor` docs for the full picture,
  /// including its one known gap (doesn't cover the TUN adapter itself
  /// disappearing, only xray crashing under it).
  Future<void> setKillSwitch({required bool enabled});

  /// `tun_fd` is ignored on Windows (which manages its own wintun adapter)
  /// and required on Android (the fd comes from `VpnService.Builder.establish()`
  /// on the Kotlin side). Kept as one signature, rather than two cfg-gated
  /// methods, so a single frb codegen pass produces one Dart API usable on
  /// both platforms.
  Future<void> startTunnel({
    required String proxyUrl,
    required String serverIp,
    int? tunFd,
    required List<String> bypassCidrs,
  });

  Future<void> startXray({
    required String xrayPath,
    required String configPath,
  });

  Future<void> stopTunnel();

  Future<void> stopXray();
}

@freezed
sealed class CharonEvent with _$CharonEvent {
  const CharonEvent._();

  const factory CharonEvent.xrayLog(String field0) = CharonEvent_XrayLog;
  const factory CharonEvent.tunnelLog(String field0) = CharonEvent_TunnelLog;
  const factory CharonEvent.tunnelStopped({required bool ok, String? message}) =
      CharonEvent_TunnelStopped;
  const factory CharonEvent.xrayStopped({int? code}) = CharonEvent_XrayStopped;

  /// Kill switch engaged: xray died unexpectedly, TUN deliberately left up
  /// so all new connections fail closed until it reconnects.
  const factory CharonEvent.blocked() = CharonEvent_Blocked;
  const factory CharonEvent.reconnecting() = CharonEvent_Reconnecting;
  const factory CharonEvent.reconnected() = CharonEvent_Reconnected;

  /// Auto-reconnect gave up on the current profile's config after
  /// exhausting all retries - the Dart side decides whether to fail over
  /// to another saved server profile.
  const factory CharonEvent.reconnectFailed() = CharonEvent_ReconnectFailed;
}
