// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1126100458;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<CharonEvent> crateApiSimpleCharonBridgeEvents({
    required CharonBridge that,
  });

  CharonBridge crateApiSimpleCharonBridgeNew();

  Future<void> crateApiSimpleCharonBridgeSetAutoReconnect({
    required CharonBridge that,
    required bool enabled,
  });

  Future<void> crateApiSimpleCharonBridgeSetKillSwitch({
    required CharonBridge that,
    required bool enabled,
  });

  Future<void> crateApiSimpleCharonBridgeStartTunnel({
    required CharonBridge that,
    required String proxyUrl,
    required String serverIp,
    int? tunFd,
    required List<String> bypassCidrs,
  });

  Future<void> crateApiSimpleCharonBridgeStartXray({
    required CharonBridge that,
    required String xrayPath,
    required String configPath,
  });

  Future<void> crateApiSimpleCharonBridgeStopTunnel({
    required CharonBridge that,
  });

  Future<void> crateApiSimpleCharonBridgeStopXray({required CharonBridge that});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CharonBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CharonBridge;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CharonBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<CharonEvent> crateApiSimpleCharonBridgeEvents({
    required CharonBridge that,
  }) {
    final sink = RustStreamSink<CharonEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
              that,
              serializer,
            );
            sse_encode_StreamSink_charon_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleCharonBridgeEventsConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeEventsConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_events",
        argNames: ["that", "sink"],
      );

  @override
  CharonBridge crateApiSimpleCharonBridgeNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCharonBridgeNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeNewConstMeta =>
      const TaskConstMeta(debugName: "CharonBridge_new", argNames: []);

  @override
  Future<void> crateApiSimpleCharonBridgeSetAutoReconnect({
    required CharonBridge that,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCharonBridgeSetAutoReconnectConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeSetAutoReconnectConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_set_auto_reconnect",
        argNames: ["that", "enabled"],
      );

  @override
  Future<void> crateApiSimpleCharonBridgeSetKillSwitch({
    required CharonBridge that,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCharonBridgeSetKillSwitchConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeSetKillSwitchConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_set_kill_switch",
        argNames: ["that", "enabled"],
      );

  @override
  Future<void> crateApiSimpleCharonBridgeStartTunnel({
    required CharonBridge that,
    required String proxyUrl,
    required String serverIp,
    int? tunFd,
    required List<String> bypassCidrs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
            that,
            serializer,
          );
          sse_encode_String(proxyUrl, serializer);
          sse_encode_String(serverIp, serializer);
          sse_encode_opt_box_autoadd_i_32(tunFd, serializer);
          sse_encode_list_String(bypassCidrs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCharonBridgeStartTunnelConstMeta,
        argValues: [that, proxyUrl, serverIp, tunFd, bypassCidrs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeStartTunnelConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_start_tunnel",
        argNames: ["that", "proxyUrl", "serverIp", "tunFd", "bypassCidrs"],
      );

  @override
  Future<void> crateApiSimpleCharonBridgeStartXray({
    required CharonBridge that,
    required String xrayPath,
    required String configPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
            that,
            serializer,
          );
          sse_encode_String(xrayPath, serializer);
          sse_encode_String(configPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCharonBridgeStartXrayConstMeta,
        argValues: [that, xrayPath, configPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeStartXrayConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_start_xray",
        argNames: ["that", "xrayPath", "configPath"],
      );

  @override
  Future<void> crateApiSimpleCharonBridgeStopTunnel({
    required CharonBridge that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCharonBridgeStopTunnelConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeStopTunnelConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_stop_tunnel",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleCharonBridgeStopXray({
    required CharonBridge that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCharonBridgeStopXrayConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCharonBridgeStopXrayConstMeta =>
      const TaskConstMeta(
        debugName: "CharonBridge_stop_xray",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CharonBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CharonBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  CharonBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CharonBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CharonBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CharonBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CharonBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CharonBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<CharonEvent> dco_decode_StreamSink_charon_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CharonEvent dco_decode_charon_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CharonEvent_XrayLog(dco_decode_String(raw[1]));
      case 1:
        return CharonEvent_TunnelLog(dco_decode_String(raw[1]));
      case 2:
        return CharonEvent_TunnelStopped(
          ok: dco_decode_bool(raw[1]),
          message: dco_decode_opt_String(raw[2]),
        );
      case 3:
        return CharonEvent_XrayStopped(
          code: dco_decode_opt_box_autoadd_i_32(raw[1]),
        );
      case 4:
        return CharonEvent_Blocked();
      case 5:
        return CharonEvent_Reconnecting();
      case 6:
        return CharonEvent_Reconnected();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  CharonBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CharonBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CharonBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CharonBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CharonBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CharonBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<CharonEvent> sse_decode_StreamSink_charon_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  CharonEvent sse_decode_charon_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return CharonEvent_XrayLog(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return CharonEvent_TunnelLog(var_field0);
      case 2:
        var var_ok = sse_decode_bool(deserializer);
        var var_message = sse_decode_opt_String(deserializer);
        return CharonEvent_TunnelStopped(ok: var_ok, message: var_message);
      case 3:
        var var_code = sse_decode_opt_box_autoadd_i_32(deserializer);
        return CharonEvent_XrayStopped(code: var_code);
      case 4:
        return CharonEvent_Blocked();
      case 5:
        return CharonEvent_Reconnecting();
      case 6:
        return CharonEvent_Reconnected();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    CharonBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CharonBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    CharonBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CharonBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCharonBridge(
    CharonBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CharonBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_charon_event_Sse(
    RustStreamSink<CharonEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_charon_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_charon_event(CharonEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CharonEvent_XrayLog(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case CharonEvent_TunnelLog(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case CharonEvent_TunnelStopped(ok: final ok, message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(ok, serializer);
        sse_encode_opt_String(message, serializer);
      case CharonEvent_XrayStopped(code: final code):
        sse_encode_i_32(3, serializer);
        sse_encode_opt_box_autoadd_i_32(code, serializer);
      case CharonEvent_Blocked():
        sse_encode_i_32(4, serializer);
      case CharonEvent_Reconnecting():
        sse_encode_i_32(5, serializer);
      case CharonEvent_Reconnected():
        sse_encode_i_32(6, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CharonBridgeImpl extends RustOpaque implements CharonBridge {
  // Not to be used by end users
  CharonBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CharonBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CharonBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CharonBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CharonBridgePtr,
  );

  /// Must be called exactly once per `CharonBridge` instance; forwards
  /// every `AppEvent` (xray/tunnel logs, connection lifecycle, kill-switch
  /// and reconnect state) to the returned Dart stream for the lifetime of
  /// the app. The supervisor already handles the Windows network-reset
  /// safety net and reconnect decisions internally, so this is a plain
  /// relay.
  Stream<CharonEvent> events() =>
      RustLib.instance.api.crateApiSimpleCharonBridgeEvents(that: this);

  /// When on, an unexpected xray or tunnel drop is retried automatically
  /// (up to 5 attempts, 5s apart) instead of just reporting the failure.
  Future<void> setAutoReconnect({required bool enabled}) => RustLib.instance.api
      .crateApiSimpleCharonBridgeSetAutoReconnect(that: this, enabled: enabled);

  /// When on, an unexpected xray crash leaves the TUN adapter in place
  /// (new connections fail closed) instead of tearing the tunnel down -
  /// see `charon_core::supervisor::Supervisor` docs for the full picture,
  /// including its one known gap (doesn't cover the TUN adapter itself
  /// disappearing, only xray crashing under it).
  Future<void> setKillSwitch({required bool enabled}) => RustLib.instance.api
      .crateApiSimpleCharonBridgeSetKillSwitch(that: this, enabled: enabled);

  /// `tun_fd` is ignored on Windows (which manages its own wintun adapter)
  /// and required on Android (the fd comes from `VpnService.Builder.establish()`
  /// on the Kotlin side). Kept as one signature, rather than two cfg-gated
  /// methods, so a single frb codegen pass produces one Dart API usable on
  /// both platforms.
  Future<void> startTunnel({
    required String proxyUrl,
    required String serverIp,
    int? tunFd,
    required List<String> bypassCidrs,
  }) => RustLib.instance.api.crateApiSimpleCharonBridgeStartTunnel(
    that: this,
    proxyUrl: proxyUrl,
    serverIp: serverIp,
    tunFd: tunFd,
    bypassCidrs: bypassCidrs,
  );

  Future<void> startXray({
    required String xrayPath,
    required String configPath,
  }) => RustLib.instance.api.crateApiSimpleCharonBridgeStartXray(
    that: this,
    xrayPath: xrayPath,
    configPath: configPath,
  );

  Future<void> stopTunnel() =>
      RustLib.instance.api.crateApiSimpleCharonBridgeStopTunnel(that: this);

  Future<void> stopXray() =>
      RustLib.instance.api.crateApiSimpleCharonBridgeStopXray(that: this);
}
